# Generated by Django 5.1.3 on 2025-11-25 17:54

from django.db import migrations

def default_roles(apps, schema_editor):
    role = apps.get_model('role', 'Role')
    role.objects.create(name='Director', description='Director, permisos especiales')
    role.objects.create(name='Administrador', description='Administrador, permisos especiales')
    role.objects.create(name='Cliente', description='Cliente, gestionar sus  matrículas')
    role.objects.create(name='Entrenador', description='Entrenador, gestionar las asistencias')

class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(default_roles),
    ]
